# Generated by Django 5.0.3 on 2024-03-14 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submition',
            new_name='Submission',
        ),
    ]
