# Generated by Django 5.0.3 on 2024-03-14 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_rename_submition_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='date_time',
            field=models.DateField(),
        ),
    ]
